### ISSUE TITLE
Status 401

### ISSUE THREAD

**Issue by PierreBresson** [woothemes/wc-api-node#19]
Hi,

I don't succeed to connect to my woocommerce, I get a status 401 instead.

Here is my code : 

```
var WooCommerceAPI = require('woocommerce-api');

var WooCommerce = new WooCommerceAPI({
  url: 'http://www.mywebsite.com/',
  wpAPI: true,
  version: 'wc/v1',
  consumerKey: 'ck_myKey',
  consumerSecret: 'cs_mySecret'
});
WooCommerce.get('', function(err, data, res) {
  console.log(res);
});
```

And get the following message : 

`{"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}`

I'm sure of my consumerKey and consumerSecret (did it many times to be sure).

Any idea why I get a 401 status ?

Thanks :)

PS: I'm using WooCommerce Version 2.6.0-beta-4

**Comment by claudiosmweb** [comment]
Try our  2.6.0-RC1, we changed some things.

**Comment by claudiosmweb** [comment]
@PierreBresson sorry! Fixed in 1.3.2 :)

**Comment by PierreBresson** [comment]
No problem ;) 

I updated to 1.3.2, but I still have the same message:

`{"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}`

(I also tested it on tonicdev to be sure)

**Comment by PierreBresson** [comment]
@claudiosmweb now it's working, thanks ;)

**Comment by maganap** [comment]
If request is made using HTTPS, it does work, as suggested above.

But in any case, this authentication issue is still happening if request is made through HTTP, WC 2.6.4.
