### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by vjijardar** [woothemes/wc-api-node#20]
var WooCommerceAPI = require('woocommerce-api');

var WooCommerce = new WooCommerceAPI({
  url: 'http://localhost:8080/demo', // Your store URL
  consumerKey: 'ck_xxxxxxxxxxxxxxxxxxxxxx', // Your consumer key
  consumerSecret: 'cs_xxxxxxxxxxxxxxxxxxxxxxx', // Your consumer secret
  wpAPI: true, // Enable the WP REST API integration
  version: 'wc/v1' // WooCommerce WP REST API version
});

WooCommerce.get('products', function(err, data, res) {
  console.log(res);
});

{"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - p
rovided signature does not match.","data":{"status":401}}
 i'm already install oauth-1.0a and express js & Dependencies .
Regard 
VIJAY

**Comment by claudiosmweb** [comment]
Fixed in v1.3.2.

**Comment by vjijardar** [comment]
Thank for reply 
But still getting same issue i'm update all as latest version.

**Comment by vjijardar** [comment]
Thanks issue solved after install Woo -RC1 version and regenerate API key
Thank you.
